import { SlideType } from "./models"
export const slideTemplates: SlideType[] = [
  {
    id: "",
    height: 720,
    width: 1280,
    nodes: [
      {
        id: "",
        type: "Text",
        value: "Click to change title",
        x: 100,
        y: 100,
        width: 1000,
        height: 80,
        fontSize: 64,
        textAlign: "left",
      },
      {
        id: "",
        type: "Text",
        value: "Click to change text",
        x: 100,
        y: 240,
        width: 440,
        height: 400,
        fontSize: 18,
        textAlign: "left",
      },
      {
        id: "",
        type: "Text",
        value: "Click to change text",
        x: 640,
        y: 240,
        width: 440,
        height: 400,
        fontSize: 18,
        textAlign: "left",
      },
    ],
  },
  {
    id: "",
    height: 720,
    width: 1280,
    nodes: [
      {
        id: "",
        type: "Text",
        value: "Click to change title",
        x: 100,
        y: 100,
        width: 1000,
        height: 80,
        fontSize: 64,
        textAlign: "left",
      },
      {
        id: "",
        type: "Text",
        value: "Click to change text",
        x: 100,
        y: 240,
        width: 440,
        height: 400,
        fontSize: 18,
        textAlign: "left",
      },
      {
        id: "",
        type: "Chart",
        x: 640,
        y: 240,
        width: 440,
        height: 400,
      },
    ],
  },
]
